import { useState, useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { ChevronRightIcon } from '@heroicons/react/20/solid'
import Layout from '../../components/Layout.js'
import { useSupabaseClient } from '@supabase/auth-helpers-react'

export default function Contacts() {
  const [contacts, setContacts] = useState([])
  const supabase = useSupabaseClient()
  useEffect(() => {
    (async () => {
      let { data, error, status } = await supabase
        .from('contacts')
        .select(`*`)
      setContacts(data)
    })()
  }, [supabase])
  return (
    <Layout>
      <Head>
        <title>Edubet - Contact list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='flex justify-center mb-4 text-4xl font-extrabold tracking-tight leading-none md:text-5xl lg:text-6xl text-neutralTitle pb-8'>
        Liste des messages de contact
      </h1>
      <div className="not-prose -my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div className="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
          <div className="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
            <table className="min-w-full divide-y divide-onNeutralBg">
              <thead className="bg-neutralBg">
                <tr>
                  <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-onNeutralBg sm:pl-6">
                    Prénom
                  </th>
                  <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-onNeutralBg">
                    Nom de famille
                  </th>
                  <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-onNeutralBg">
                    Email
                  </th>
                  <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-onNeutralBg">
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-onNeutralBg bg-neutralBg">
                {contacts.map((contact) => (
                  <tr key={contact.email}>
                    <td className="whitespace-nowrap px-3 py-4 text-sm text-onNeutralBg">{contact.firstname}</td>
                    <td className="whitespace-nowrap px-3 py-4 text-sm text-onNeutralBg">{contact.lastname}</td>
                    <td className="whitespace-nowrap px-3 py-4 text-sm text-onNeutralBg">{contact.email}</td>
                    <td>
                      <Link
                        className={"w-5 h-5 block bg-slate-200 hover:bg-onPrimaryBg hover:text-white rounded-full"}
                        href={`/admin/contacts/${contact.id}`}
                      >
                        <ChevronRightIcon className="h-5 w-5 " aria-hidden="true" />
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </Layout>
  )
}
